name: CI

on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v3.3.0
      - run: rustup component add rustfmt
      - name: fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build_cache
    steps:
      - uses: actions/checkout@v3.3.0
      - run: rustup component add clippy
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build_cache
    steps:
      - uses: actions/checkout@v3.3.0
      - name: test
        run: cargo test --all -- --nocapture