name: CI

on:
  push:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
        version:
          - stable
      name: ${{ matrix.target.name }} / ${{ matrix.version }}
      runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v3.3.0

      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: test
        run: cargo test --all -- --nocapture
